dist: bionic
language: go

env:
  global:
    - GO111MODULE=on
    - GOLANGCI_LINT_VERSION=1.19.1

cache:
  directories:
    - ${HOME}/.cache/go-build
    - ${GOPATH}/pkg/mod
  npm: true
  yarn: true

_lint_job: &lint_job
  env: CACHE_NAME=lint
  before_install:
    - if [ -f .github/.ci.conf ]; then . .github/.ci.conf; fi
  install: skip
  before_script:
    - |
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
        | bash -s - -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}
  script:
    - bash .github/lint-filename.sh
    - golangci-lint run ./...

_build_job: &build_job
  env: CACHE_NAME=build
  script:
    - go build ./cmd/server/grpc/main.go
    - go build ./cmd/server/json-rpc/main.go

_build_sfu_docker_job: &build_sfu_docker_job
  env: CACHE_NAME=build_sfu_docker
  script:
    - docker build --tag pionwebrtc/ion-sfu:latest .
  before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag pionwebrtc/ion-sfu:latest pionwebrtc/ion-sfu:"$TRAVIS_TAG"
  deploy:
    provider: script
    script: docker push pionwebrtc/ion-sfu:latest && docker push pionwebrtc/ion-sfu:"$TRAVIS_TAG"
    on:
      tags: true

_test_job: &test_job
  env: CACHE_NAME=test
  before_install:
    - if [ -f .github/.ci.conf ]; then . .github/.ci.conf; fi
  script:
    - make test
    - if [ -n "${TEST_HOOK}" ]; then ${TEST_HOOK}; fi
  after_success:
    - travis_retry bash <(curl -s https://codecov.io/bash) -c -F go

jobs:
  include:
    - <<: *lint_job
      name: Lint 1.14
      go: 1.14
      if: branch = master OR tag IS present
    - <<: *build_job
      name: Build 1.13
      go: 1.13
      if: branch = master OR tag IS present
    - <<: *build_job
      name: Build 1.14
      go: 1.14
      if: branch = master OR tag IS present
    - <<: *test_job
      name: Test 1.13
      go: 1.13
      if: branch = master OR tag IS present
    - <<: *test_job
      name: Test 1.14
      go: 1.14
      if: branch = master OR tag IS present
    - <<: *build_sfu_docker_job
      name: Build sfu docker
      if: branch = master OR tag IS present

notifications:
  email: false
